CREATE TABLE QUEUE_SOURCE
(
  seq INT NOT NULL,
  status INT NOT NULL,
  value VARCHAR(64) NOT NULL,
  CONSTRAINT PK_QUEUE_SOURCE PRIMARY KEY (seq)
);

INSERT INTO QUEUE_SOURCE VALUES (1, 0, 'その１');
INSERT INTO QUEUE_SOURCE VALUES (2, 0, 'その２');
INSERT INTO QUEUE_SOURCE VALUES (3, 0, 'その３');
INSERT INTO QUEUE_SOURCE VALUES (4, 0, 'その４');
INSERT INTO QUEUE_SOURCE VALUES (5, 0, 'その５');
INSERT INTO QUEUE_SOURCE VALUES (6, 0, 'その６');
INSERT INTO QUEUE_SOURCE VALUES (7, 0, 'その７');
INSERT INTO QUEUE_SOURCE VALUES (8, 0, 'その８');
INSERT INTO QUEUE_SOURCE VALUES (9, 0, 'その９');
INSERT INTO QUEUE_SOURCE VALUES (10, 0, 'その１０');
