{
 "title": "Kafka Consumer Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "Topic",
    "query": "kafka_consumer_records_lag_records"
   }
  ]
 },
 "panels": [
  { "title": "Consumer Select", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "kafka_consumer_select_total (1m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(kafka_consumer_select_total[1m])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  { "title": "Kafka Consumser Group Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "kafka_consumergroup_group_lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_group_lag{topic=\"$topic\"}",
     "legendFormat": "{{group}}, partition = {{partition}}"
    }
   ]
  },
  {
   "title": "kafka_consumergroup_group_lag_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_group_lag_seconds{topic=\"$topic\"}",
     "legendFormat": "{{group}}, partition = {{partition}}"
    }
   ]
  },
  { "title": "Consumer Records Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "kafka_consumer_records_lag_records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_records_lag_records{topic=\"$topic\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "kafka_consumer_records_lag_avg_records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_records_lag_avg_records",
     "legendFormat": "{{client_id}}, partition = {{partition}}"
    }
   ]
  },
  {
   "title": "kafka_consumer_records_lag_max_records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_records_lag_max_records",
     "legendFormat": "{{client_id}}, partition = {{partition}}"
    }
   ]
  },
  { "title": "Consumer Fetch Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "kafka_consumer_fetch_latency_avg_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_latency_avg_seconds",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "kafka_consumer_fetch_latency_max_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_latency_max_seconds",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  { "title": "Consumer Commit Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "kafka_consumer_commit_latency_avg_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_commit_latency_avg_seconds",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "kafka_consumer_commit_latency_max_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_commit_latency_max_seconds",
     "legendFormat": "{{client_id}}"
    }
   ]
  }
 ]
}