{
 "title": "Kafka Lag Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(kafka_consumergroup_group_lag)"
   },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": "query_result(kafka_consumergroup_group_lag{namespace=\"$namespace\"})"
   },
   {
    "name": "consumer_group",
    "label": "Consumer Group",
    "query": "query_result(kafka_consumergroup_group_lag{namespace=\"$namespace\",cluster_name=\"$cluster_name\"})"
   }
  ]
 },
 "panels": [
  { "title": "All Consumer Group Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consumer Group Max Lag Seconds",
   "type": "graph",
   "description": "Max extrapolated lag in seconds for each consumer group.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s", "label": "estimated lag in seconds" }
   ],
   "targets": [
    {
     "expr": "topk(50, kafka_consumergroup_group_max_lag_seconds{namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\"})",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag Partition Seconds",
   "type": "graph",
   "description": "Extrapolated lag in seconds for each partition.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s", "label": "estimated lag in seconds" }
   ],
   "targets": [
    {
     "expr": "topk(25, kafka_consumergroup_group_lag_seconds{namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\"})",
     "legendFormat": "{{group}},{{topic}},{{partition}}"
    }
   ]
  },
  {
   "title": "Consumer Group Max Lag Offsets",
   "type": "graph",
   "description": "Max offset lag for each consumer group.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "offsets" }
   ],
   "targets": [
    {
     "expr": "topk(50, kafka_consumergroup_group_max_lag{namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\"})",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag Partition Offsets",
   "type": "graph",
   "description": "Consumer Group Lag Partition Offsets",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "offsets" }
   ],
   "targets": [
    {
     "expr": "topk(25, kafka_consumergroup_group_lag{namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\"})",
     "legendFormat": "{{group}},{{topic}},{{partition}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag In Time Per Group Over Offset Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }
  },
  {
   "title": "$consumer_group",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "repeat": "consumer_group",
   "yaxes": [
    { "format": "s", "label": "estimated lag in seconds" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_group_max_lag_seconds{namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\"}",
     "legendFormat": "Consumer group lag in time"
    },
    {
     "expr": "kafka_consumergroup_group_max_lag{namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\"}",
     "legendFormat": "Consumer group lag in offsets"
    }
   ]
  },
  {
   "title": "Consumer Group Lag in Time Per Group Over Summed Offsets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "$consumer_group",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "repeat": "consumer_group",
   "yaxes": [
    { "format": "s", "label": "estimated lag in seconds" }
   ],
   "targets": [
    {
     "expr": "max(kafka_consumergroup_group_lag_seconds{namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\"}) by (group)",
     "legendFormat": "Consumer group lag in time"
    },
    {
     "expr": "sum(kafka_consumergroup_group_offset{namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\"})",
     "legendFormat": "Sum of group offsets"
    },
    {
     "expr": "sum((kafka_consumergroup_group_offset{namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\"} * 0)\n+ on(namespace,cluster_name,topic,partition) group_left() kafka_partition_latest_offset{namespace=\"$namespace\",cluster_name=\"$cluster_name\"})",
     "legendFormat": "Sum of latest offsets"
    }
   ]
  },
  { "title": "Kafka Lag Exporter JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_memory_bytes_used{instance=~\"kafka-lag-exporter.*\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{instance=~\"kafka-lag-exporter.*\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM GC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_count{instance=~\"kafka-lag-exporter.*\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}